import type { PlatformTheme } from "@/lib/types";

const base = (
  label: string,
  overrides: Partial<PlatformTheme> = {},
): PlatformTheme => ({
  primary: "#0088cc",
  secondary: "#f0f0f0",
  bubbleSent: "#dcf8c6",
  bubbleReceived: "#ffffff",
  headerBg: "#075e54",
  headerText: "#ffffff",
  background: "#e5ddd5",
  backgroundDark: "#0b141a",
  accent: "#25d366",
  fontFamily: "system-ui, -apple-system, sans-serif",
  borderRadius: "8px",
  platformLabel: label,
  ...overrides,
});

export const PLATFORM_THEMES: Record<string, PlatformTheme> = {
  whatsapp: base("WhatsApp", {
    primary: "#075e54",
    bubbleSent: "#dcf8c6",
    bubbleReceived: "#ffffff",
    headerBg: "#075e54",
    background: "#e5ddd5",
    backgroundDark: "#0b141a",
    accent: "#25d366",
  }),
  telegram: base("Telegram", {
    primary: "#0088cc",
    bubbleSent: "#effdde",
    bubbleReceived: "#ffffff",
    headerBg: "#517da2",
    background: "#ffffff",
    accent: "#0088cc",
  }),
  signal: base("Signal", {
    primary: "#2c6bed",
    bubbleSent: "#2c6bed",
    bubbleReceived: "#e8e8e8",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#2c6bed",
  }),
  wechat: base("WeChat", {
    primary: "#07c160",
    bubbleSent: "#95ec69",
    bubbleReceived: "#ffffff",
    headerBg: "#ededed",
    headerText: "#000000",
    background: "#ededed",
    accent: "#07c160",
  }),
  line: base("LINE", {
    primary: "#06c755",
    bubbleSent: "#8de055",
    bubbleReceived: "#ffffff",
    headerBg: "#06c755",
    background: "#8cabd9",
    accent: "#06c755",
  }),
  messenger: base("Messenger", {
    primary: "#0084ff",
    bubbleSent: "#0084ff",
    bubbleReceived: "#e4e6eb",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#0084ff",
    borderRadius: "18px",
  }),
  imessage: base("iMessage", {
    primary: "#007aff",
    bubbleSent: "#007aff",
    bubbleReceived: "#e5e5ea",
    headerBg: "#f6f6f6",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#007aff",
    borderRadius: "18px",
    fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif",
  }),
  "tech-texts": base("Tech Texts", {
    primary: "#34c759",
    bubbleSent: "#34c759",
    bubbleReceived: "#e5e5ea",
    headerBg: "#000000",
    background: "#000000",
    backgroundDark: "#000000",
    accent: "#34c759",
    borderRadius: "18px",
  }),
  slack: base("Slack", {
    primary: "#4a154b",
    bubbleSent: "#ffffff",
    bubbleReceived: "#ffffff",
    headerBg: "#350d36",
    background: "#ffffff",
    accent: "#e01e5a",
    borderRadius: "4px",
  }),
  teams: base("Microsoft Teams", {
    primary: "#6264a7",
    bubbleSent: "#e8ebfa",
    bubbleReceived: "#f5f5f5",
    headerBg: "#6264a7",
    background: "#f5f5f5",
    accent: "#6264a7",
    borderRadius: "4px",
  }),
  discord: base("Discord", {
    primary: "#5865f2",
    bubbleSent: "#5865f2",
    bubbleReceived: "#40444b",
    headerBg: "#36393f",
    headerText: "#ffffff",
    background: "#36393f",
    backgroundDark: "#2f3136",
    accent: "#5865f2",
    borderRadius: "8px",
  }),
  tinder: base("Tinder", {
    primary: "#fe3c72",
    bubbleSent: "#fe3c72",
    bubbleReceived: "#f0f0f0",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#fe3c72",
    borderRadius: "20px",
  }),
  bumble: base("Bumble", {
    primary: "#ffc629",
    bubbleSent: "#ffc629",
    bubbleReceived: "#f0f0f0",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#ffc629",
    borderRadius: "20px",
  }),
  instagram: base("Instagram", {
    primary: "#e1306c",
    bubbleSent: "#3797f0",
    bubbleReceived: "#efefef",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#e1306c",
    borderRadius: "22px",
  }),
  snapchat: base("Snapchat", {
    primary: "#fffc00",
    bubbleSent: "#3d3d3d",
    bubbleReceived: "#efefef",
    headerBg: "#fffc00",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#fffc00",
    borderRadius: "16px",
  }),
  tiktok: base("TikTok", {
    primary: "#fe2c55",
    bubbleSent: "#fe2c55",
    bubbleReceived: "#f1f1f1",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#25f4ee",
    borderRadius: "16px",
  }),
  x: base("X", {
    primary: "#1d9bf0",
    bubbleSent: "#1d9bf0",
    bubbleReceived: "#eff3f4",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#1d9bf0",
    borderRadius: "16px",
  }),
  bluesky: base("Bluesky", {
    primary: "#0085ff",
    bubbleSent: "#0085ff",
    bubbleReceived: "#f0f0f0",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#0085ff",
    borderRadius: "16px",
  }),
  chatgpt: base("ChatGPT", {
    primary: "#10a37f",
    bubbleSent: "#f7f7f8",
    bubbleReceived: "#f7f7f8",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    backgroundDark: "#343541",
    accent: "#10a37f",
    borderRadius: "8px",
  }),
  claude: base("Claude", {
    primary: "#d97757",
    bubbleSent: "#e8d5c4",
    bubbleReceived: "#faf8f5",
    headerBg: "#faf8f5",
    headerText: "#1a1a1a",
    background: "#faf8f5",
    accent: "#d97757",
    borderRadius: "18px",
  }),
  gemini: base("Gemini", {
    primary: "#4285f4",
    bubbleSent: "#f0f4f9",
    bubbleReceived: "#f0f4f9",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#4285f4",
    borderRadius: "12px",
  }),
  grok: base("Grok", {
    primary: "#000000",
    bubbleSent: "#f0f0f0",
    bubbleReceived: "#f0f0f0",
    headerBg: "#000000",
    headerText: "#ffffff",
    background: "#ffffff",
    backgroundDark: "#000000",
    accent: "#000000",
    borderRadius: "12px",
  }),
  perplexity: base("Perplexity", {
    primary: "#20b8cd",
    bubbleSent: "#f3f3f3",
    bubbleReceived: "#f3f3f3",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#20b8cd",
    borderRadius: "12px",
  }),
  linkedin: base("LinkedIn", {
    primary: "#0a66c2",
    bubbleSent: "#d9ecff",
    bubbleReceived: "#f0f0f0",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#f3f2ef",
    accent: "#0a66c2",
    borderRadius: "8px",
  }),
  reddit: base("Reddit", {
    primary: "#ff4500",
    bubbleSent: "#ff4500",
    bubbleReceived: "#f6f7f8",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#ff4500",
    borderRadius: "20px",
  }),
  msn: base("MSN", {
    primary: "#0078d4",
    bubbleSent: "#cce4f7",
    bubbleReceived: "#ffffff",
    headerBg: "#0078d4",
    background: "#e8f4fc",
    accent: "#0078d4",
    borderRadius: "4px",
  }),
  onlyfans: base("OnlyFans", {
    primary: "#00aff0",
    bubbleSent: "#00aff0",
    bubbleReceived: "#f0f0f0",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#00aff0",
    borderRadius: "16px",
  }),
  facebook: base("Facebook", {
    primary: "#1877f2",
    bubbleSent: "#0084ff",
    bubbleReceived: "#e4e6eb",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#f0f2f5",
    accent: "#1877f2",
    borderRadius: "18px",
  }),
  youtube: base("YouTube", {
    primary: "#ff0000",
    bubbleSent: "#ff0000",
    bubbleReceived: "#f1f1f1",
    headerBg: "#ffffff",
    headerText: "#0f0f0f",
    background: "#ffffff",
    backgroundDark: "#0f0f0f",
    accent: "#ff0000",
    borderRadius: "8px",
  }),
  pinterest: base("Pinterest", {
    primary: "#e60023",
    bubbleSent: "#e60023",
    bubbleReceived: "#ffffff",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#e60023",
    borderRadius: "16px",
  }),
  threads: base("Threads", {
    primary: "#000000",
    bubbleSent: "#f0f0f0",
    bubbleReceived: "#ffffff",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#000000",
    borderRadius: "8px",
  }),
  gmail: base("Gmail", {
    primary: "#ea4335",
    bubbleSent: "#ffffff",
    bubbleReceived: "#ffffff",
    headerBg: "#ffffff",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#ea4335",
    borderRadius: "0px",
  }),
  outlook: base("Outlook", {
    primary: "#0078d4",
    bubbleSent: "#ffffff",
    bubbleReceived: "#ffffff",
    headerBg: "#0078d4",
    headerText: "#ffffff",
    background: "#f3f2f1",
    accent: "#0078d4",
    borderRadius: "0px",
  }),
  "apple-mail": base("Apple Mail", {
    primary: "#007aff",
    bubbleSent: "#ffffff",
    bubbleReceived: "#ffffff",
    headerBg: "#f6f6f6",
    headerText: "#000000",
    background: "#ffffff",
    accent: "#007aff",
    borderRadius: "0px",
    fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif",
  }),
  "redacted-email": base("Redacted Email", {
    primary: "#333333",
    bubbleSent: "#ffffff",
    bubbleReceived: "#ffffff",
    headerBg: "#1a1a1a",
    headerText: "#ffffff",
    background: "#f5f5f5",
    accent: "#333333",
    borderRadius: "0px",
  }),
};

export function getTheme(slug: string): PlatformTheme {
  return PLATFORM_THEMES[slug] ?? base(slug);
}
